const SAO_PAULO_TIMEZONE  = "America/Sao_Paulo"
const INTERVAL = 4
const INTERVAL_PERIOD = "HOUR" 
const NAME_EMISOR_INTERNO = "EMISSOR INTERNO"
const OPERACAO_TIPO_WALLET_IN = "WALLET-IN"
const OPERACAO_TIPO_WALLET_OUT = "WALLET-OUT"
const OPERACAO_TIPO_TRADING_OUT = "TRADING-OUT"
const OPERACAO_TIPO_TRADING_IN = "TRADING-IN"

module.exports = { 
    SAO_PAULO_TIMEZONE,
    INTERVAL,
    INTERVAL_PERIOD,
    NAME_EMISOR_INTERNO,
    OPERACAO_TIPO_WALLET_IN,
    OPERACAO_TIPO_WALLET_OUT,
    OPERACAO_TIPO_TRADING_OUT,
    OPERACAO_TIPO_TRADING_IN
    };